In [1]:
import pandas as pd

In [2]:
rate = pd.read_csv("/Users/alexmahadevan/Desktop/UNEMPLOYMENT RATE.csv")

In [3]:
jobs = pd.read_csv("/Users/alexmahadevan/Desktop/JOBS.csv")

In [4]:
rate.head(1)

  METRO_OR_STATE  2016_RATE  2017_RATE
0        Alabama        6.3        5.2

In [15]:
rate['RATE_CHANGE'] = (rate['2017_RATE'] - rate['2016_RATE']) / rate['2016_RATE']

In [6]:
jobs.head(1)

  STATE_OR_METRO  EMPLOYED_CHANGE  PERCENT_CHANGE
0        Alabama             34.8             1.8

In [13]:
jobs.sort_values("PERCENT_CHANGE" , ascending=False)

                     STATE_OR_METRO  EMPLOYED_CHANGE  PERCENT_CHANGE
176                       Manhattan              3.2             7.8
67                     Fort Collins             11.6             7.2
106                         Sebring              1.4             5.7
339                            Enid              1.5             5.4
175                        Lawrence              2.7             5.4
193                    Lake Charles              5.6             5.2
434                      St. George              3.1             5.1
61                        Yuba City              2.1             5.0
2                    Auburn-Opelika              3.0             4.8
132                      Boise City             14.7             4.8
25                             Yuma              2.4             4.6
135                        Lewiston              1.3             4.6
394                       Cleveland              2.1             4.6
97    North Port-Sarasota-Bradenton             12.9             4.4
433                      Provo-Orem             10.4             4.4
91                      Gainesville              5.9             4.4
154                  Elkhart-Goshen              5.8             4.4
168      Des Moines-West Des Moines             15.5             4.3
107                     Tallahassee              7.3             4.2
28   Fayetteville-Springdale-Rogers             10.2             4.2
213                     New Bedford              2.9             4.2
266                          Nevada             53.4             4.1
119                     Gainesville              3.5             4.1
100   Palm Bay-Melbourne-Titusville              8.5             4.1
400                      Morristown              1.8             4.1
42                           Madera              1.5             4.1
104                     Punta Gorda              1.9             4.1
99        Orlando-Kissimmee-Sanford             47.2             4.0
432                Ogden-Clearfield              9.9             4.0
105            Sebastian-Vero Beach              1.9             3.9
..                              ...              ...             ...
217                             NaN              NaN             NaN
233                             NaN              NaN             NaN
240                             NaN              NaN             NaN
245                             NaN              NaN             NaN
255                             NaN              NaN             NaN
260                             NaN              NaN             NaN
265                             NaN              NaN             NaN
270                             NaN              NaN             NaN
275                             NaN              NaN             NaN
281                             NaN              NaN             NaN
287                             NaN              NaN             NaN
301                             NaN              NaN             NaN
318                             NaN              NaN             NaN
323                             NaN              NaN             NaN
337                             NaN              NaN             NaN
343                             NaN              NaN             NaN
353                             NaN              NaN             NaN
373                             NaN              NaN             NaN
376                             NaN              NaN             NaN
386                             NaN              NaN             NaN
390                             NaN              NaN             NaN
402                             NaN              NaN             NaN
429                             NaN              NaN             NaN
436                             NaN              NaN             NaN
439                             NaN              NaN             NaN
450                             NaN              NaN             NaN
463                             NaN              NaN             NaN
471                             NaN              NaN             NaN
485                             NaN              NaN             NaN
489                             NaN              NaN             NaN

[498 rows x 3 columns]

In [14]:
jobs.sort_values("PERCENT_CHANGE")

               STATE_OR_METRO  EMPLOYED_CHANGE  PERCENT_CHANGE
487                    Casper             -1.5            -3.8
191           Houma-Thibodaux             -2.8            -3.2
247            Cape Girardeau             -1.3            -2.9
465                   Beckley             -1.0            -2.2
16                  Fairbanks             -0.8            -2.1
492                   Arecibo             -0.6            -1.8
490               Puerto Rico            -12.4            -1.4
421                San Angelo             -0.6            -1.2
335   Weirton-Steubenville(1)             -0.5            -1.2
497  San Juan-Carolina-Caguas             -6.8            -1.1
315               Rocky Mount             -0.6            -1.1
78                  Waterbury             -0.7            -1.0
196   Shreveport-Bossier City             -1.9            -1.0
424                 Texarkana             -0.6            -1.0
474                Eau Claire             -0.8            -0.9
188                Alexandria             -0.5            -0.8
29                 Fort Smith             -0.9            -0.8
486                   Wyoming             -2.4            -0.8
230                  Muskegon             -0.5            -0.8
310                Greenville             -0.6            -0.8
221                  Bay City             -0.3            -0.8
143                  Danville             -0.2            -0.7
493                   Guayama             -0.1            -0.7
160    Michigan City-La Porte             -0.3            -0.7
284                Farmington             -0.3            -0.6
320                  Bismarck             -0.4            -0.5
292                    Elmira             -0.2            -0.5
206                Cumberland             -0.2            -0.5
192                 Lafayette             -1.1            -0.5
495                     Ponce             -0.3            -0.4
..                        ...              ...             ...
217                       NaN              NaN             NaN
233                       NaN              NaN             NaN
240                       NaN              NaN             NaN
245                       NaN              NaN             NaN
255                       NaN              NaN             NaN
260                       NaN              NaN             NaN
265                       NaN              NaN             NaN
270                       NaN              NaN             NaN
275                       NaN              NaN             NaN
281                       NaN              NaN             NaN
287                       NaN              NaN             NaN
301                       NaN              NaN             NaN
318                       NaN              NaN             NaN
323                       NaN              NaN             NaN
337                       NaN              NaN             NaN
343                       NaN              NaN             NaN
353                       NaN              NaN             NaN
373                       NaN              NaN             NaN
376                       NaN              NaN             NaN
386                       NaN              NaN             NaN
390                       NaN              NaN             NaN
402                       NaN              NaN             NaN
429                       NaN              NaN             NaN
436                       NaN              NaN             NaN
439                       NaN              NaN             NaN
450                       NaN              NaN             NaN
463                       NaN              NaN             NaN
471                       NaN              NaN             NaN
485                       NaN              NaN             NaN
489                       NaN              NaN             NaN

[498 rows x 3 columns]

In [16]:
rate.head(1)

  METRO_OR_STATE  2016_RATE  2017_RATE  RATE_CHANGE
0        Alabama        6.3        5.2    -0.174603

In [19]:
rate.sort_values("RATE_CHANGE" , ascending=False)

                        METRO_OR_STATE  2016_RATE  2017_RATE  RATE_CHANGE
299                             Toledo        4.7        6.2     0.319149
165            Elizabethtown-Fort Knox        4.7        5.4     0.148936
168                          Owensboro        4.8        5.4     0.125000
166                  Lexington-Fayette        4.0        4.5     0.125000
293                   Cleveland-Elyria        5.7        6.4     0.122807
193                         Pittsfield        4.4        4.9     0.113636
164                      Bowling Green        4.5        5.0     0.111111
192                        New Bedford        5.4        6.0     0.111111
15                           Fairbanks        5.7        6.3     0.105263
188                      Massachusetts        4.0        4.4     0.100000
348                        Sioux Falls        2.3        2.5     0.086957
259  Buffalo-Cheektowaga-Niagara Falls        4.7        5.1     0.085106
295                             Dayton        4.7        5.1     0.085106
296                               Lima        4.9        5.3     0.081633
190            Boston-Cambridge-Nashua        3.7        4.0     0.081081
194                        Springfield        5.0        5.4     0.080000
289                               Ohio        5.0        5.4     0.080000
189                    Barnstable Town        3.8        4.1     0.078947
297                          Mansfield        5.2        5.6     0.076923
74                               Dover        5.3        5.7     0.075472
163                           Kentucky        5.3        5.7     0.075472
347                         Rapid City        2.8        3.0     0.071429
346                       South Dakota        2.8        3.0     0.071429
292                         Cincinnati        4.4        4.7     0.068182
384                               Waco        4.5        4.8     0.066667
265                          Rochester        4.5        4.8     0.066667
381                          Texarkana        4.6        4.9     0.065217
262                             Ithaca        4.6        4.9     0.065217
267                         Utica-Rome        4.6        4.9     0.065217
73                            Delaware        4.7        5.0     0.063830
..                                 ...        ...        ...          ...
119                              Idaho        3.7        2.7    -0.270270
310                          Corvallis        4.8        3.5    -0.270833
65                              Pueblo        5.5        4.0    -0.272727
141                         Evansville        4.4        3.2    -0.272727
223                           Columbia        4.0        2.9    -0.275000
60                    Colorado Springs        4.3        3.1    -0.279070
122                        Idaho Falls        3.2        2.3    -0.281250
123                           Lewiston        3.9        2.8    -0.282051
436                            Wyoming        5.6        4.0    -0.285714
61              Denver-Aurora-Lakewood        3.5        2.5    -0.285714
285                       North Dakota        3.5        2.5    -0.285714
58                            Colorado        3.7        2.6    -0.297297
148               South Bend-Mishawaka        4.7        3.3    -0.297872
376                            Midland        5.0        3.5    -0.300000
143       Indianapolis-Carmel-Anderson        4.2        2.9    -0.309524
437                             Casper        7.7        5.3    -0.311688
139                           Columbus        3.5        2.4    -0.314286
137                            Indiana        4.6        3.1    -0.326087
145           Lafayette-West Lafayette        4.5        3.0    -0.333333
147                             Muncie        5.7        3.8    -0.333333
138                        Bloomington        5.4        3.6    -0.333333
62                        Fort Collins        3.2        2.1    -0.343750
146             Michigan City-La Porte        5.8        3.8    -0.344828
200            Detroit-Warren-Dearborn        5.7        3.7    -0.350877
377                             Odessa        7.3        4.7    -0.356164
64                             Greeley        3.9        2.5    -0.358974
149                        Terre Haute        5.8        3.7    -0.362069
142                         Fort Wayne        4.4        2.8    -0.363636
140                     Elkhart-Goshen        3.7        2.3    -0.378378
63                      Grand Junction        6.1        3.6    -0.409836

[447 rows x 4 columns]

In [20]:
rate.sort_values("RATE_CHANGE")

                        METRO_OR_STATE  2016_RATE  2017_RATE  RATE_CHANGE
63                      Grand Junction        6.1        3.6    -0.409836
140                     Elkhart-Goshen        3.7        2.3    -0.378378
142                         Fort Wayne        4.4        2.8    -0.363636
149                        Terre Haute        5.8        3.7    -0.362069
64                             Greeley        3.9        2.5    -0.358974
377                             Odessa        7.3        4.7    -0.356164
200            Detroit-Warren-Dearborn        5.7        3.7    -0.350877
146             Michigan City-La Porte        5.8        3.8    -0.344828
62                        Fort Collins        3.2        2.1    -0.343750
147                             Muncie        5.7        3.8    -0.333333
138                        Bloomington        5.4        3.6    -0.333333
145           Lafayette-West Lafayette        4.5        3.0    -0.333333
137                            Indiana        4.6        3.1    -0.326087
139                           Columbus        3.5        2.4    -0.314286
437                             Casper        7.7        5.3    -0.311688
143       Indianapolis-Carmel-Anderson        4.2        2.9    -0.309524
376                            Midland        5.0        3.5    -0.300000
148               South Bend-Mishawaka        4.7        3.3    -0.297872
58                            Colorado        3.7        2.6    -0.297297
285                       North Dakota        3.5        2.5    -0.285714
61              Denver-Aurora-Lakewood        3.5        2.5    -0.285714
436                            Wyoming        5.6        4.0    -0.285714
123                           Lewiston        3.9        2.8    -0.282051
122                        Idaho Falls        3.2        2.3    -0.281250
60                    Colorado Springs        4.3        3.1    -0.279070
223                           Columbia        4.0        2.9    -0.275000
141                         Evansville        4.4        3.2    -0.272727
65                              Pueblo        5.5        4.0    -0.272727
310                          Corvallis        4.8        3.5    -0.270833
119                              Idaho        3.7        2.7    -0.270270
..                                 ...        ...        ...          ...
73                            Delaware        4.7        5.0     0.063830
262                             Ithaca        4.6        4.9     0.065217
267                         Utica-Rome        4.6        4.9     0.065217
381                          Texarkana        4.6        4.9     0.065217
265                          Rochester        4.5        4.8     0.066667
384                               Waco        4.5        4.8     0.066667
292                         Cincinnati        4.4        4.7     0.068182
346                       South Dakota        2.8        3.0     0.071429
347                         Rapid City        2.8        3.0     0.071429
74                               Dover        5.3        5.7     0.075472
163                           Kentucky        5.3        5.7     0.075472
297                          Mansfield        5.2        5.6     0.076923
189                    Barnstable Town        3.8        4.1     0.078947
289                               Ohio        5.0        5.4     0.080000
194                        Springfield        5.0        5.4     0.080000
190            Boston-Cambridge-Nashua        3.7        4.0     0.081081
296                               Lima        4.9        5.3     0.081633
295                             Dayton        4.7        5.1     0.085106
259  Buffalo-Cheektowaga-Niagara Falls        4.7        5.1     0.085106
348                        Sioux Falls        2.3        2.5     0.086957
188                      Massachusetts        4.0        4.4     0.100000
15                           Fairbanks        5.7        6.3     0.105263
192                        New Bedford        5.4        6.0     0.111111
164                      Bowling Green        4.5        5.0     0.111111
193                         Pittsfield        4.4        4.9     0.113636
293                   Cleveland-Elyria        5.7        6.4     0.122807
166                  Lexington-Fayette        4.0        4.5     0.125000
168                          Owensboro        4.8        5.4     0.125000
165            Elizabethtown-Fort Knox        4.7        5.4     0.148936
299                             Toledo        4.7        6.2     0.319149

[447 rows x 4 columns]